fashion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recommender/', include('recommender.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/recommender/', permanent=True)),
]
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('/__debug__/', include(debug_toolbar.urls)), 
#     ] + urlpatterns

recommender/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.index, name = 'index'),
	path('recommended/', views.RecommendedListView, name = 'recommended'),
	path('item/<int:pk>', views.ItemDetailView, name = 'item-detail'),
	path('item/like/', views.ItemLikeToggleView, name = 'like-toggle'),
	path('item/likes', views.ItemLikeAllToggleView, name = 'like-all-toggle'),
	path('items/liked/like', views.ItemsLikedToggleView, name = 'liked-items-toggle'),
	path('items', views.ItemsAllView.as_view(), name = 'items'),
	path('items/liked/<int:pk>', views.AllLikedItemsView, name = 'allliked'),
	path('preference/filter', views.PreferenceFilterView, name = 'preference-filter'),
	path('user/statistics', views.ChartView, name = 'stats'),
]

recommender/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
	
class Item(models.Model):
	
	item_type = models.CharField(max_length = 200, null = True, blank = True)
	price = models.CharField(max_length = 200, null = True, blank = True)
	color = models.CharField(max_length = 200, null = True, blank = True)
	image_URL = models.CharField(max_length = 1000, null = True, blank = True)
	fit = models.CharField(max_length = 200, null = True, blank = True)
	occasion = models.CharField(max_length = 200, null = True, blank = True)
	brand = models.CharField(max_length = 200, null = True, blank = True)
	pattern = models.CharField(max_length = 200, null = True, blank = True)
	fabric = models.CharField(max_length = 200, null = True, blank = True)
	gender = models.CharField(max_length = 1, null = True, blank = True)
	length = models.CharField(max_length = 200, null = True, blank = True)
	likes = models.ManyToManyField(User, blank = True, related_name = 'item_likes')

	def get_absolute_url(self):
		"""Returns the url to access a detail record for this item"""
		return reverse('item-detail', args = [str(self.id)])
		
	def get_total_likes(self):
		return self.likes.count()

	def get_items(self):
		return reverse('items')

	def get_random_liked_url(self):
		return reverse('index')

recommender/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(help_text = 'Enter username', max_length = 254, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
	password = forms.CharField(help_text = 'Enter password', max_length = 20, widget = forms.PasswordInput(attrs={'placeholder':'Password'}))

	def clean(self):
		cleaned_data  = super(LoginForm, self).clean()
		username = cleaned_data.get('username')
		password = cleaned_data.get('password')
		if not username:
			raise forms.ValidationError('Please enter username')
		elif not password:
			raise forms.ValidationError('Please enter password')

class PreferenceForm(forms.Form):
	FILTER_CHOICES = (
		('item_type', 'Type (e.g jeans, t-shirts)'),
		('color', 'Color'),
		('fit', 'Fit'),
		('occasion', 'Occasion'),
		('pattern', 'Pattern'),
		('fabric', 'Fabric'),
		('length', 'Length'),
	)
	preferences = forms.ChoiceField(choices = FILTER_CHOICES)

recommender/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from recommender.forms import LoginForm
from recommender.models import Item
from django.views import generic
from django.views.generic import RedirectView
from django.db.models import Max, Count
from django.db import connection
from django.http import HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from collections import defaultdict
from django.urls import reverse
from threading import Thread
import queue
import time
import json
from django.contrib import messages


def index(request):
	random_items = Item.objects.order_by('?').only('id','image_URL')[:21]
	ids = []
	urls = []
	for i in random_items:
		ids.append(i.id)
	total_likes = Item.objects.only('id').filter(id__in = ids)
	total_likes_list = []
	for i in total_likes:
		total_likes_list.append(i.get_total_likes())
	random = zip(random_items,total_likes_list)
	print(random)
	context = {

		'index_active_page': 'active',
		'random_items': random
	}
	return render(request, 'index.html', context)

def PreferenceFilterView(request):
	item_ids = []
	user_prefs = []
	ids = request.GET.get('ids')
	prefs = request.GET.get('filters')
	ids = ids.replace('[', '')
	ids = ids.replace(']', '')
	ids = ids.replace("'", '')
	ids = ids.replace(' ', '')
	prefs = prefs.replace('[', '')
	prefs = prefs.replace(']', '')
	prefs = prefs.replace('"', '')
	item_ids.append(ids.split(","))
	user_prefs.append(prefs.split(","))
	item_ids = tuple(item_ids)
	user_prefs = tuple(user_prefs)
	print(user_prefs)
	items = []
	if len(user_prefs[0]) == 1:
		if user_prefs[0][0] in 'M' or user_prefs[0][0] in 'F':
			for i in Item.objects.filter(id__in = item_ids[0]).filter(gender__in = user_prefs[0][0]).only('image_URL').values('image_URL'):
				items.append(i['image_URL'])
		else:
			for i in Item.objects.filter(id__in = item_ids[0]).filter(item_type__in = user_prefs[0]).only('image_URL').values('image_URL'):
				items.append(i['image_URL'])

	else:
		for i in Item.objects.filter(id__in = item_ids[0]).filter(item_type__in = user_prefs[0], gender__in = user_prefs[0]).only('image_URL').values('image_URL'):
			items.append(i['image_URL'])
		

	#print(items)
	context = {
		'items': items,
	}
	if request.is_ajax():
		html = render_to_string('recommender/filter_section.html', context, request = request)
		return JsonResponse({'form': html})



@login_required
def RecommendedListView(request):
	model = Item
	template_name = 'recommender/recommended.html'
	paginate_by = 10
	context = {
		'recommended_active_page': 'active'
	}
	
	def calculate_dice_coe(random_items, pks, liked_index_list, upl, column_mapping, pref, queue):
		desc_coe_list = []
		dice_coe = defaultdict(int)
		top_val_1 = []
		for i,pk in zip(range(len(random_items)),pks):
				if pk in liked_index_list:
					continue
				
				for j in range(0,8):

					if random_items is None: 
						continue
					else:
						if random_items[i][j] in upl[j]:
							#print(random_items[i][j])
							#print(upl[j])
							if column_mapping[pref] == j:
								top_val_1.append(2)
								#print(top_val_1)
							else:
								top_val_1.append(0.5)
								#print(top_val_1)
							

				top = sum(top_val_1)
				bottom = 11
				dice_coe[str(pk)] = round((2*top)/bottom,3)
				top_val_1.clear()
				#print(dice_coe)

		desc_coe_dict = sorted(dice_coe, key = dice_coe.get, reverse = True)
		for value in desc_coe_dict:
			#print(dice_coe[value])
			#print(value)
			desc_coe_list.append(value)

		#print(desc_coe_list[:11])
		desc_coe_list1 = desc_coe_list[:21]
		#print(desc_coe_list1)
		rec = tuple([int(i) for i in desc_coe_list1])
		urls = []
		ids = []
		item = []
		#urls = Item.objects.raw('SELECT image_URL FROM recommender_item WHERE id in %s',[rec])
		for u in Item.objects.filter(id__in = rec).only('id', 'image_URL').values('id', 'image_URL'):
			urls.append(u['image_URL'])
			ids.append(u['id'])
			

		for u in Item.objects.filter(id__in = rec).only('item_type').values('item_type'):
			item.append(u['item_type'])
		
		data_rec = zip(urls,ids)
		context = {
			'rec': data_rec,
			'type': item,
			'ids': ids
			
		}
		queue.put(context)
		
	
	def get_sim(pref, liked_index_list, user_preference_list):
		pk_list = []
		pks = []
		random_items = []
		context = {}
		upl = user_preference_list.copy()
		print(upl)
		#print(pref)
		column_mapping = {'item_type': 0, 'color': 1, 'fit': 2, 'occasion': 3, 'brand': 4, 'pattern': 5, 'fabric':6, 'length': 7}
		lastkey = Item.objects.only('id').order_by('-id').first()
		#print(lastkey.id)
		firstkey = Item.objects.only('id').order_by('id').first()
		#print(firstkey.id)
		start_time1 = time.time()
		for pk in Item.objects.only('id').values('id'):
			if pk['id'] in liked_index_list:
				continue
			else:
				pks.append(pk['id'])
		#print(time.time() - start_time1)
		#print(len(pks))
		start_time2 = time.time()
		item_queue = queue.Queue()

		def retrieve_items(fk, lk, liked_index_list, item_queue):
			for i in range(fk,lk):
				if i in liked_index_list:
					continue
				random_item = Item.objects.only('item_type', 'color', 'fit', 'occasion', 'brand', 'pattern', 'fabric', 'length').filter(id=i).values_list('item_type', 'color', 'fit', 'occasion', 'brand', 'pattern', 'fabric', 'length').first()		
				random_items.append(random_item)
			item_queue.put(random_items)

		thread = Thread(target = retrieve_items, args = (int(firstkey.id), int(lastkey.id), liked_index_list, item_queue))
		thread.start()
		thread.join()
		random_items = item_queue.get()
		#print('Time for retrieving tuples')
		#print(time.time() - start_time2)
		try:
			queued_req1 = queue.Queue()
			start_time3 = time.time()
			thread1 = Thread(target = calculate_dice_coe, args = (random_items, pks, liked_index_list, upl, column_mapping, pref, queued_req1,))	
			thread1.start()	
			thread1.join()
			context = queued_req1.get()
			#print(time.time() - start_time3)
			#print(context)
			return context
		except:
			print('Exception occured')
			traceback.print_exc()
		finally:
			connection.close()

	def get_preference_list(liked_index_list, pref):
		def item_sql(liked_index_list):
			str11 = 'SELECT id,max(mycount),item_type FROM (SELECT id,item_type, COUNT(item_type) mycount FROM recommender_item where id in ('
			str12 = ','.join(map(str,liked_index_list))
			str13 = ') GROUP BY item_type)'
			q2 = str11 + str12 + str13
			count = Item.objects.raw(q2)
			return count
		def color_sql(liked_index_list):
			str11 = 'SELECT id,max(mycount),color FROM (SELECT id,color, COUNT(color) mycount FROM recommender_item where id in ('
			str12 = ','.join(map(str,liked_index_list))
			str13 = ') GROUP BY color)'
			q2 = str11 + str12 + str13
			count = Item.objects.raw(q2)
			return count
		def fit_sql(liked_index_list):
			none_check = 'N/A'
			str11 = 'SELECT id,max(mycount),fit FROM (SELECT id,fit, COUNT(fit) mycount FROM recommender_item where fit is not'
			str12 = "'"+none_check+"'"
			str13 = 'and'
			str14 = ' id in ('
			str15 = ','.join(map(str,liked_index_list))
			str16 = ') GROUP BY fit)'
			q2 = str11 + str12 + str13 + str14 + str15 + str16
			count = Item.objects.raw(q2)
			return count
		def occasion_sql(liked_index_list):
			str11 = 'SELECT id,max(mycount),occasion FROM (SELECT id,occasion, COUNT(occasion) mycount FROM recommender_item where id in ('
			str12 = ','.join(map(str,liked_index_list))
			str13 = ') GROUP BY occasion)'
			q2 = str11 + str12 + str13
			count = Item.objects.raw(q2)
			return count
		def brand_sql(liked_index_list):
			str11 = 'SELECT id,max(mycount),brand FROM (SELECT id,brand, COUNT(brand) mycount FROM recommender_item where id in ('
			str12 = ','.join(map(str,liked_index_list))
			str13 = ') GROUP BY brand)'
			q2 = str11 + str12 + str13
			count = Item.objects.raw(q2)
			return count
		def pattern_sql(liked_index_list):
			none_check = 'N/A'
			str11 = 'SELECT id,max(mycount),pattern FROM (SELECT id,pattern, COUNT(pattern) mycount FROM recommender_item where pattern is not' 
			str12 = "'"+none_check+"'"
			str13 = 'and'
			str14 = ' id in ('
			str15 = ','.join(map(str,liked_index_list))
			str16 = ') GROUP BY pattern)'
			q2 = str11 + str12 + str13 + str14 + str15 +str16
			count = Item.objects.raw(q2)

			return count
		def fabric_sql(liked_index_list):
			str11 = 'SELECT id,max(mycount),fabric FROM (SELECT id,fabric, COUNT(fabric) mycount FROM recommender_item where id in ('
			str12 = ','.join(map(str,liked_index_list))
			str13 = ') GROUP BY fabric)'
			q2 = str11 + str12 + str13
			count = Item.objects.raw(q2)
			return count
		def length_sql(liked_index_list):
			str11 = 'SELECT id,max(mycount),length FROM (SELECT id,length, COUNT(length) mycount FROM recommender_item where id in ('
			str12 = ','.join(map(str,liked_index_list))
			str13 = ') GROUP BY length)'
			q2 = str11 + str12 + str13
			count = Item.objects.raw(q2)
			return count

		item_count = item_sql(liked_index_list)
		color_count = color_sql(liked_index_list)  
		fit_count = fit_sql(liked_index_list)
		occasion_count =  occasion_sql(liked_index_list)
		brand_count = brand_sql(liked_index_list)
		pattern_count = pattern_sql(liked_index_list)
		fabric_count = fabric_sql(liked_index_list)
		length_count = length_sql(liked_index_list)
		# print(item_count)
		# print(color_count)
		# print(fit_count)
		# print(occasion_count)
		# print(brand_count) 
		# print(pattern_count)
		# print(fabric_count)
		# print(length_count)
		user_preference_list = []
		for a,b,c,d,e,f,g,h in zip(item_count, color_count, fit_count, occasion_count, brand_count, pattern_count, fabric_count, length_count):
			user_preference_list.extend([a.item_type, b.color, c.fit, d.occasion, e.brand, f.pattern, g.fabric, h.length ])
		
		return get_sim(pref, liked_index_list, user_preference_list)

	def liked_item_ids(pref):
		def liked_ids_sql():
			with connection.cursor() as cursor:

recommender/templates/recommender/all_items.html
{% extends 'base_generic.html' %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% block content %}
	<h1>Items</h1>
	<ul>
		{% for item in item_list %}
			<li><a href="{% url 'item-detail' item.id %}">{{ item.image_URL }}</a></li>
		{% endfor %}
	</ul>
{% endblock %}

recommender/templates/recommender/all_liked.html
{% extends 'base_generic.html' %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% block content %}
<h1>Liked Items</h1>
	<div class="row">
		{% for i,l in likes %}
			<div class="column">
				<a href="{% url 'item-detail' i.id %}"><img src="{{ i.image_URL }}" alt="Unable to load image at this moment"></a>

				<div id="like-all-section-{{i.id}}">
					{% include 'recommender/all_liked_toggle_section.html' %}

				</div>
	
			</div>
		{% endfor %}
		
	</div>

{% endblock %}

recommender/templates/recommender/all_liked_toggle_section.html
{% if user.is_authenticated %}
	<form action="{% url 'liked-items-toggle' %}" method="POST">
		{% csrf_token %}
		{% if is_liked %}
			<button type="submit" name="item_id" id="liked_item_btn" class="btn btn-danger" value="{{ i.id }}" >Dislike</button>
		{% else %}
			<button type="submit" name="item_id" id="liked_item_btn" class="btn btn-primary" value="{{ item.id }}" >Like</button>
		{% endif %}
	</form>
{% endif %}

{% if total_likes >= 0 %}
	{% if total_likes == 1 %}
		{{ total_likes }} person has liked this item
	{% elif total_likes == 0 %}
		No one has liked this item yet
	{% else %}
		
		{{ total_likes }} people have liked this item
	{% endif %}
{% else %}
	{% if l == 1 %}
		{{ l }} person has liked this item
	{% elif l == 0 %}
		No one has liked this item yet
	{% else %}
		{{ l }} people have liked this item
	{% endif %}
{% endif %}

recommender/templates/recommender/filter_section.html
<div id="preference-filter">
	<div class="panel-group">
	  <div class="panel panel-default">
	    <div class="panel-heading" style="margin-top: 1em;">
	      <h4 class="panel-title">
	        <a data-toggle="collapse" href="#collapse1">Filters</a>
	      </h4>
	    </div>
	    <div id="collapse1" class="panel-collapse collapse">
	      <div class="panel-body">
	      	<form action="{% url 'preference-filter' %}" method="POST">
		{% csrf_token %}


			<label>
				<input type="checkbox" name="pref"  value="tshirts">T-shirts
			</label>
			<label>
				<input type="checkbox" name="pref" value="shirts">Shirts
			</label>
			<label>
				<input type="checkbox" name="pref" value="jeans">Jeans

			</label>
			<label>
				<input type="checkbox" name="pref" value="kurtas">Kurtas

			</label>
			<label>
				<input type="checkbox" name="pref" value="tops">Tops

			</label>
			<label>
				<input type="checkbox" name="pref" value="dresses">Dresses

			</label>
			<label>
				<input type="checkbox" name="pref" value="skirts">Skirts

			</label>
			<label>
				<input type="checkbox" name="pref" value="shorts">Shorts

			</label>
			<label>
				<input type="checkbox" name="pref" value="kurta-sets">Kurta sets

			</label>
			<label>
				<input type="checkbox" name="pref" value="leggings">Leggings

			</label>
			<label>
				<input type="checkbox" name="pref" value="tights">Tights

			</label>
			<label>
				<input type="checkbox" name="pref" value="track-pants">Trackpants
			</label>
			<label>
				<input type="checkbox" name="pref" value="trousers">Trousers
			</label>
			<label>
				<input type="checkbox" name="pref" value="M">Male
			</label>
			<label>
				<input type="checkbox" name="pref" value="F">Female
			</label>
			<button class="btn btn-primary" type="submit" id="filter-button">Filter</button>

		
	</form>
	      </div>
	      
	    </div>
	  </div>
	</div>
	
	
	
</div>	
<div id="filtered-div" class="row">
	{% for i in items %}
					<div class="column">
						<a href=""><img src="{{ i }}"></a>
					</div>
	{% endfor %}			
</div>

recommender/templates/recommender/item_detail.html
{% extends 'base_generic.html' %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% block content %}


	<h1>Item detail</h1>
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="panel panel-default">
			  	<div class="panel-body">
			  		<img src="{{ item.image_URL }}" alt="Image could not be loaded at this moment">
			  	</div>
			 </div>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12">
			<div class="panel panel-default">
				<div class="panel-body">
			  		<ul class="list-group">
						<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Type: {{ item.item_type }}</li>
						<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Color: {{ item.color }}</li>
						{% if item.fit not in 'N/A' %}
							<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Fit: {{ item.fit }}</li>
						{% endif %}
						<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Occasion: {{ item.occasion }}</li>
						<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Brand: {{ item.brand }}</li>
						{% if item.pattern|length > 0 or item.pattern not in 'N/A' %}
							<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Pattern: {{ item.pattern }}</li>
						{% endif %}
						<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Fabric: {{ item.fabric }}</li>
						<li class="list-group-item" style="padding: 1.1rem 1.25rem;">Length: {{ item.length }}</li>
						<!--<li>Likes: {{ item.likes.count }} <a href="{{ item.get_like_url }}">Like</a></li>-->
						
						<div id="like-section" style="padding-top: 2em;">
							{% include 'recommender/like_section.html' %}
						</div>

					</ul>
		  		
		  	</div>
			</div>
		</div>
	</div>
		
		  	
		
	
	
{% endblock %}

recommender/templates/recommender/like_all_section.html
{% if user.is_authenticated %}
	<form action="{% url 'like-all-toggle' %}" method="POST">
		{% csrf_token %}
		{% if is_liked %}
			<button type="submit" name="item_id" id="like_btn_all" class="btn btn-danger" value="{{ item.id }}" >Dislike</button>
		{% else %}
			<button type="submit" name="item_id" id="like_btn_all" class="btn btn-primary" value="{{ item.id }}" >Like</button>
		{% endif %}
	</form>
{% endif %}
{% if total_likes >= 0 %}
	{% if total_likes == 1 %}
		{{ total_likes }} person has liked this item
	{% elif total_likes == 0 %}
		No one has liked this item yet
	{% else %}
		{{ total_likes }} people have liked this item
	{% endif %}
{% else %}
	{% if l == 1 %}
		{{ l }} person has liked this item
	{% elif l == 0 %}
		No one has liked this item yet
	{% else %}
		{{ l }} people have liked this item
	{% endif %}
{% endif %}

	

recommender/templates/recommender/like_section.html
{% if user.is_authenticated %}
<form action="{% url 'like-toggle' %}" method="POST">
	{% csrf_token %}
	{% if is_liked %}
		<button type="submit" name="item_id" id="like_btn" class="btn btn-danger" value="{{ item.id }}" >Dislike</button>
	{% else %}
		<button type="submit" name="item_id" id="like_btn" class="btn btn-primary" value="{{ item.id }}" >Like</button>
	{% endif %}

</form> 
{% endif %}
{% if total_likes == 1 %}
	{{ total_likes }} person has liked this item
{% elif total_likes == 0 %}
	No one has liked this item yet
{% else %}
	{{ total_likes }} people have liked this item
{% endif %}

recommender/templates/recommender/recommended.html
{% extends 'base_generic.html' %}
{% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% block content %}
<head>
<script type="text/javascript">
	
	$(document).ready(function(event){
		$('#recommend-button').attr('disabled', 'disabled');
		

		function checkDropdown(){
			
			if (buttonDisable()) {
				console.log('called')
				$("#recommend-button").removeClass("btn btn-danger");
				$("#recommend-button").addClass("btn btn-success");
		        $('#recommend-button').attr('disabled', false);
		  

		    } else {
		        $('#recommend-button').attr('disabled', 'disabled');
		       
		    }
		}
		function buttonDisable(){
			if ($('#preferences').val() != '' ) {

	        	return true;
	    	} else {
	        	return false;
	    	}

		}
		$('#preferences').change(checkDropdown);
	});
		
	$(document).ready(function(event){
		
        $(document).on('click', '#filter-button', function(event){
        	event.preventDefault()
            var filters = []
            var rec_ids = {{ ids|safe }}
            
            $.each($("input[name='pref']:checked"), function(){
            		filters.push($(this).val());

            });
            
            $.ajax({
            	type: 'GET',
            	url: '{% url "preference-filter" %}',
            	data:{
            		'ids': '{{ ids }}',
            		'filters': JSON.stringify(filters),
            		'csrfmiddlewaretoken': '{{ csrf_token }}'

            	},
            	dataType: 'json',
            	success: function(response){
            		$('#preference-filter').html(response['form'])
            		$('#recommended-div').fadeOut()
            		

            		console.log($('#preference-filter').html(response['form']));
            	},
            	error: function(rs, e){
            		console.log(rs.responseText)
            	},
            });
     
        });
    });
    $(document).ready(function(event){

        $(document).on('click', '#cancel-button', function(event){
        	$('#recommended-div').fadeIn()
        	$('#filtered-div').fadeOut()
			    
        });
    });
    $(document).ready(function(event){
        $('input[type=checkbox]').prop('checked',false);		
    });

    
</script>
</head>
<h1>Recommended items</h1>

	<form action="{% url 'recommended' %}" method="POST" >
		{% csrf_token %}
		
		<select id="preferences" name="preferences">
			<option selected="Preference" value=''>Select preference</option>
			<option value="item_type">Type</option>
			<option value="color">Color</option>
			<option value="fit">Fit</option>
			<option value="occasion">Occasion</option>
			<option value="pattern">Pattern</option>
			<option value="fabric">Fabric</option>
			<option value="length">Length</option>

		</select>
		<br>
		<button class="btn btn-danger" type="submit" name="recommend-button" id="recommend-button" style="margin-top: 1em;">Recommend</button>
	</form>
	

	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li>{{ message }}</li>
			{% endfor %}

		</ul>
	
	{% else %}
		
		{% if rec %}
			{% include 'recommender/filter_section.html' %}
			<button class="btn btn-warning" name="cancel-button" id="cancel-button" style="margin-top: 0.2em;color:white;">Cancel filters</button>
		{% endif %}
		
			
			<div id="recommended-div" class="row">
			{% for u,i in rec %}

				<div class="column">
					<a href="{% url 'item-detail' i %}"><img src="{{ u }}" alt="Unable to load image at this moment"></a>
				</div>
				
			
			{% endfor %}
			</div>
	
		
			
	{% endif %}

{% endblock %}